import { useEffect, useState, useMemo } from 'react';
import { useSpotify } from '../hooks/useSpotify';
import { useAuthStore } from '../store/useAuthStore';
import TrackCard from '../components/cards/TrackCard';
import ArtistCard from '../components/cards/ArtistCard';

const TIME_RANGES = [
  { key: 'short_term', label: '4_WEEKS' },
  { key: 'medium_term', label: '6_MONTHS' },
  { key: 'long_term', label: 'ALL_TIME' },
];

const VIEW_TYPES = [
  { key: 'tracks', label: 'TRACKS' },
  { key: 'artists', label: 'ARTISTS' },
];

export default function Archive() {
  const { getTopItems, createPlaylist, addTracksToPlaylist } = useSpotify();
  const { user } = useAuthStore();
  const [timeRange, setTimeRange] = useState('medium_term');
  const [viewType, setViewType] = useState('tracks');
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [notification, setNotification] = useState(null);

  // Popularity-based filtering (works without Audio Features API)
  const [minPopularity, setMinPopularity] = useState(0);

  const filteredTracks = useMemo(() => {
    if (viewType !== 'tracks' || minPopularity === 0) return items;
    return items.filter(track => (track.popularity || 0) >= minPopularity);
  }, [items, minPopularity, viewType]);

  // Load top items
  useEffect(() => {
    async function load() {
      setLoading(true);
      try {
        const data = await getTopItems(viewType, timeRange, 50);
        setItems(data.items || []);
      } catch (err) {
        console.error('[DATA_VAULT] Load error:', err);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [timeRange, viewType]);

  const handleCreatePlaylist = async () => {
    if (!user?.id || viewType !== 'tracks' || filteredTracks.length === 0) return;

    setCreating(true);
    try {
      const rangeLabel = TIME_RANGES.find(t => t.key === timeRange)?.label || timeRange;
      const name = `ANDROMEDA // Filtered — ${rangeLabel}`;
      const desc = `Auto-generated by ANDROMEDA // OS. ${filteredTracks.length} tracks filtered (POP≥${minPopularity}%).`;

      const playlist = await createPlaylist(user.id, name, desc);
      const uris = filteredTracks.map(t => t.uri);
      await addTracksToPlaylist(playlist.id, uris);

      setNotification({ type: 'success', message: `Playlist "${name}" created with ${filteredTracks.length} tracks!` });
      setTimeout(() => setNotification(null), 5000);
    } catch (err) {
      setNotification({ type: 'error', message: err.message });
      setTimeout(() => setNotification(null), 5000);
    } finally {
      setCreating(false);
    }
  };

  const displayItems = viewType === 'tracks' ? filteredTracks : items;

  return (
    <div className="pt-20 pb-24 px-4 max-w-7xl mx-auto animate-fade-in">
      {/* Header */}
      <div className="flex items-center gap-2 mb-6">
        <span className="w-1.5 h-1.5 bg-accent-cyan" />
        <h1 className="text-[11px] font-mono text-slate-400 tracking-[0.2em]">
          DATA_VAULT // ARCHIVE
        </h1>
      </div>

      {/* Notification */}
      {notification && (
        <div
          className={`fui-panel clip-angular-sm p-3 mb-4 animate-slide-up
            ${notification.type === 'success' ? 'border-accent-cyan/40' : 'border-accent-red/40'}`}
        >
          <span className={`text-sm font-mono ${notification.type === 'success' ? 'text-accent-cyan' : 'text-accent-red'}`}>
            {notification.type === 'success' ? '✓' : '⚠'} {notification.message}
          </span>
        </div>
      )}

      {/* Time Range Filters */}
      <div className="flex flex-wrap items-center gap-4 mb-4">
        <div className="flex items-center gap-1 fui-panel p-1">
          {TIME_RANGES.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setTimeRange(key)}
              className={`px-3 py-1.5 text-[10px] font-mono tracking-wider transition-all duration-300
                ${timeRange === key
                  ? 'bg-accent-fuchsia/20 text-accent-fuchsia border border-accent-fuchsia/30'
                  : 'text-slate-500 hover:text-slate-300 border border-transparent'
                }`}
            >
              [{label}]
            </button>
          ))}
        </div>

        {/* View Toggle */}
        <div className="flex items-center gap-1 fui-panel p-1">
          {VIEW_TYPES.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setViewType(key)}
              className={`px-3 py-1.5 text-[10px] font-mono tracking-wider transition-all duration-300
                ${viewType === key
                  ? 'bg-accent-cyan/20 text-accent-cyan border border-accent-cyan/30'
                  : 'text-slate-500 hover:text-slate-300 border border-transparent'
                }`}
            >
              {label}
            </button>
          ))}
        </div>

        <span className="text-[10px] font-mono text-slate-600 ml-auto">
          {displayItems.length} / {items.length} ENTRIES
        </span>
      </div>


      {/* Content */}
      {loading ? (
        <div className="grid gap-2">
          {[...Array(10)].map((_, i) => (
            <div key={i} className="skeleton h-14 w-full clip-angular-sm" />
          ))}
        </div>
      ) : displayItems.length === 0 ? (
        <div className="fui-panel clip-angular p-12 text-center">
          <span className="text-sm font-mono text-slate-500">
            {viewType === 'tracks' && minPopularity > 0
              ? 'NO TRACKS MATCH CURRENT FILTER PARAMETERS'
              : 'NO DATA IN REGISTRY'}
          </span>
        </div>
      ) : viewType === 'tracks' ? (
        <div className="grid gap-2">
          {filteredTracks.map((track, i) => (
            <TrackCard
              key={track.id}
              track={track}
              rank={i + 1}
              onPlay={() => {}}
            />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          {items.map((artist, i) => (
            <ArtistCard
              key={artist.id}
              artist={artist}
              rank={i + 1}
            />
          ))}
        </div>
      )}
    </div>
  );
}
