import { useEffect, useState } from 'react';
import { useSpotify } from '../hooks/useSpotify';
import { useAuthStore } from '../store/useAuthStore';
import { useFilteredTracks } from '../hooks/useFilteredTracks';
import TrackCard from '../components/cards/TrackCard';
import ArtistCard from '../components/cards/ArtistCard';

const TIME_RANGES = [
  { key: 'short_term', label: '4_WEEKS' },
  { key: 'medium_term', label: '6_MONTHS' },
  { key: 'long_term', label: 'ALL_TIME' },
];

const VIEW_TYPES = [
  { key: 'tracks', label: 'TRACKS' },
  { key: 'artists', label: 'ARTISTS' },
];

export default function Archive() {
  const { getTopItems, getAudioFeatures, createPlaylist, addTracksToPlaylist } = useSpotify();
  const { user } = useAuthStore();
  const [timeRange, setTimeRange] = useState('medium_term');
  const [viewType, setViewType] = useState('tracks');
  const [items, setItems] = useState([]);
  const [featuresMap, setFeaturesMap] = useState({});
  const [loading, setLoading] = useState(true);
  const [featuresLoading, setFeaturesLoading] = useState(false);
  const [creating, setCreating] = useState(false);
  const [notification, setNotification] = useState(null);

  const {
    minEnergy,
    setMinEnergy,
    minDanceability,
    setMinDanceability,
    filteredTracks,
  } = useFilteredTracks(items, featuresMap);

  // Load top items
  useEffect(() => {
    async function load() {
      setLoading(true);
      setFeaturesMap({});
      try {
        const data = await getTopItems(viewType, timeRange, 50);
        setItems(data.items || []);
      } catch (err) {
        console.error('[DATA_VAULT] Load error:', err);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [timeRange, viewType]);

  // Fetch audio features when tracks load
  useEffect(() => {
    if (viewType !== 'tracks' || items.length === 0) return;

    async function loadFeatures() {
      setFeaturesLoading(true);
      try {
        const ids = items.map(t => t.id);
        // Spotify API allows max 100 IDs per request
        const features = await getAudioFeatures(ids);
        const map = {};
        (features.audio_features || []).forEach(f => {
          if (f) map[f.id] = f;
        });
        setFeaturesMap(map);
      } catch (err) {
        console.error('[DATA_VAULT] Features error:', err);
      } finally {
        setFeaturesLoading(false);
      }
    }
    loadFeatures();
  }, [items, viewType]);

  const handleCreatePlaylist = async () => {
    if (!user?.id || viewType !== 'tracks' || filteredTracks.length === 0) return;

    setCreating(true);
    try {
      const rangeLabel = TIME_RANGES.find(t => t.key === timeRange)?.label || timeRange;
      const name = `ANDROMEDA // Filtered — ${rangeLabel}`;
      const desc = `Auto-generated by ANDROMEDA // OS. ${filteredTracks.length} tracks filtered (E≥${minEnergy}%, D≥${minDanceability}%).`;

      const playlist = await createPlaylist(user.id, name, desc);
      const uris = filteredTracks.map(t => t.uri);
      await addTracksToPlaylist(playlist.id, uris);

      setNotification({ type: 'success', message: `Playlist "${name}" created with ${filteredTracks.length} tracks!` });
      setTimeout(() => setNotification(null), 5000);
    } catch (err) {
      setNotification({ type: 'error', message: err.message });
      setTimeout(() => setNotification(null), 5000);
    } finally {
      setCreating(false);
    }
  };

  const displayItems = viewType === 'tracks' ? filteredTracks : items;

  return (
    <div className="pt-20 pb-24 px-4 max-w-7xl mx-auto animate-fade-in">
      {/* Header */}
      <div className="flex items-center gap-2 mb-6">
        <span className="w-1.5 h-1.5 bg-accent-cyan" />
        <h1 className="text-[11px] font-mono text-slate-400 tracking-[0.2em]">
          DATA_VAULT // ARCHIVE
        </h1>
      </div>

      {/* Notification */}
      {notification && (
        <div
          className={`fui-panel clip-angular-sm p-3 mb-4 animate-slide-up
            ${notification.type === 'success' ? 'border-accent-cyan/40' : 'border-accent-red/40'}`}
        >
          <span className={`text-sm font-mono ${notification.type === 'success' ? 'text-accent-cyan' : 'text-accent-red'}`}>
            {notification.type === 'success' ? '✓' : '⚠'} {notification.message}
          </span>
        </div>
      )}

      {/* Time Range Filters */}
      <div className="flex flex-wrap items-center gap-4 mb-4">
        <div className="flex items-center gap-1 fui-panel p-1">
          {TIME_RANGES.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setTimeRange(key)}
              className={`px-3 py-1.5 text-[10px] font-mono tracking-wider transition-all duration-300
                ${timeRange === key
                  ? 'bg-accent-fuchsia/20 text-accent-fuchsia border border-accent-fuchsia/30'
                  : 'text-slate-500 hover:text-slate-300 border border-transparent'
                }`}
            >
              [{label}]
            </button>
          ))}
        </div>

        {/* View Toggle */}
        <div className="flex items-center gap-1 fui-panel p-1">
          {VIEW_TYPES.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setViewType(key)}
              className={`px-3 py-1.5 text-[10px] font-mono tracking-wider transition-all duration-300
                ${viewType === key
                  ? 'bg-accent-cyan/20 text-accent-cyan border border-accent-cyan/30'
                  : 'text-slate-500 hover:text-slate-300 border border-transparent'
                }`}
            >
              {label}
            </button>
          ))}
        </div>

        <span className="text-[10px] font-mono text-slate-600 ml-auto">
          {displayItems.length} / {items.length} ENTRIES
        </span>
      </div>

      {/* Parametric Sliders (only for tracks) */}
      {viewType === 'tracks' && (
        <div className="fui-panel clip-angular p-4 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <span className="w-1.5 h-1.5 bg-accent-fuchsia" />
            <span className="text-[10px] font-mono text-slate-400 tracking-[0.2em]">PARAMETRIC FILTERS</span>
            {featuresLoading && (
              <div className="w-3 h-3 border border-accent-cyan border-t-transparent rounded-full animate-spin ml-2" />
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {/* Energy Slider */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] font-mono text-slate-500 tracking-wider">ENERGÍA MÍNIMA</span>
                <span className="text-[11px] font-mono text-accent-cyan font-bold">{minEnergy}%</span>
              </div>
              <input
                type="range"
                min={0}
                max={100}
                value={minEnergy}
                onChange={e => setMinEnergy(Number(e.target.value))}
                className="range-parametric w-full"
              />
              <div className="flex justify-between mt-1">
                <span className="text-[9px] font-mono text-slate-600">0%</span>
                <span className="text-[9px] font-mono text-slate-600">100%</span>
              </div>
            </div>

            {/* Danceability Slider */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] font-mono text-slate-500 tracking-wider">BAILABILIDAD MÍNIMA</span>
                <span className="text-[11px] font-mono text-accent-fuchsia font-bold">{minDanceability}%</span>
              </div>
              <input
                type="range"
                min={0}
                max={100}
                value={minDanceability}
                onChange={e => setMinDanceability(Number(e.target.value))}
                className="range-parametric w-full"
              />
              <div className="flex justify-between mt-1">
                <span className="text-[9px] font-mono text-slate-600">0%</span>
                <span className="text-[9px] font-mono text-slate-600">100%</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Extract to Playlist button */}
      {viewType === 'tracks' && filteredTracks.length > 0 && (
        <div className="mb-6 flex justify-center">
          <button
            id="extract-playlist-btn"
            onClick={handleCreatePlaylist}
            disabled={creating}
            className="btn-extract clip-angular text-accent-cyan"
          >
            {creating ? (
              <span className="flex items-center gap-3">
                <div className="w-4 h-4 border-2 border-accent-cyan border-t-transparent rounded-full animate-spin" />
                GENERATING PLAYLIST...
              </span>
            ) : (
              `[ EXTRACT_TO_PLAYLIST ] — ${filteredTracks.length} TRACKS`
            )}
          </button>
        </div>
      )}

      {/* Content */}
      {loading ? (
        <div className="grid gap-2">
          {[...Array(10)].map((_, i) => (
            <div key={i} className="skeleton h-14 w-full clip-angular-sm" />
          ))}
        </div>
      ) : displayItems.length === 0 ? (
        <div className="fui-panel clip-angular p-12 text-center">
          <span className="text-sm font-mono text-slate-500">
            {viewType === 'tracks' && (minEnergy > 0 || minDanceability > 0)
              ? 'NO TRACKS MATCH CURRENT FILTER PARAMETERS'
              : 'NO DATA IN REGISTRY'}
          </span>
        </div>
      ) : viewType === 'tracks' ? (
        <div className="grid gap-2">
          {filteredTracks.map((track, i) => (
            <TrackCard
              key={track.id}
              track={track}
              rank={i + 1}
              onPlay={() => {}}
            />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          {items.map((artist, i) => (
            <ArtistCard
              key={artist.id}
              artist={artist}
              rank={i + 1}
            />
          ))}
        </div>
      )}
    </div>
  );
}
